name: blockify
description: Generate and configure avatars based off of the hash of any arbitrary string content.
version: 0.2.0-dev
homepage: https://github.com/parlough/blockify

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  crypto: ^3.0.2
  image: ^3.2.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.12.1
