name: blockify
description: Generate and configure avatars based off of the hash of any arbitrary string content.
version: 0.1.0
homepage: https://github.com/parlough/blockify

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  image: ^3.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
