name: blockify
description: >
  Generate and configure avatars based on
  the hash of any arbitrary string content.
version: 1.0.0
repository: https://github.com/parlough/blockify

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.3
  image: ^4.0.17

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.24.4
